package com.evp.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * FileStats generated by hbm2java
 */
@Entity
@Table(name = "file_stats", catalog = "file_stats"
)
@XmlRootElement
public class FileStats implements java.io.Serializable
{

    private Integer fileId;
    private String fileName;
    private List<LineStats> linesStats = new ArrayList<>(0);

    public FileStats()
    {
    }

    public FileStats(String fileName)
    {
        this.fileName = fileName;
    }

    public FileStats(String fileName, List<LineStats> lineStatses)
    {
        this.fileName = fileName;
        this.linesStats = lineStatses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "file_id", unique = true, nullable = false)
    public Integer getFileId()
    {
        return this.fileId;
    }

    public void setFileId(Integer fileId)
    {
        this.fileId = fileId;
    }

    @Column(name = "file_name", nullable = false, length = 65535)
    public String getFileName()
    {
        return this.fileName;
    }

    public void setFileName(String fileName)
    {
        this.fileName = fileName;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fileStats")
    public List<LineStats> getLinesStats()
    {
        return this.linesStats;
    }

    public void setLinesStats(List<LineStats> linesStats)
    {
        this.linesStats = linesStats;
    }

}
