package com.evp.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * LineStats generated by hbm2java
 */
@Entity
@Table(name = "line_stats", catalog = "file_stats"
)
@XmlRootElement
public class LineStats implements java.io.Serializable
{

    private Integer id;
    private FileStats fileStats;
    private int lineId;
    private String longestWord;
    private String shortestWord;
    private int lineLength;
    private double avgWordLength;

    public LineStats()
    {
    }

    public LineStats(FileStats fileStats, int lineId, String longestWord, String shortestWord, int lineLength, double avgWordLength)
    {
        this.fileStats = fileStats;
        this.lineId = lineId;
        this.longestWord = longestWord;
        this.shortestWord = shortestWord;
        this.lineLength = lineLength;
        this.avgWordLength = avgWordLength;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "file_id", nullable = false)
    public FileStats getFileStats()
    {
        return this.fileStats;
    }

    public void setFileStats(FileStats fileStats)
    {
        this.fileStats = fileStats;
    }

    @Column(name = "line_id", nullable = false)
    public int getLineId()
    {
        return this.lineId;
    }

    public void setLineId(int lineId)
    {
        this.lineId = lineId;
    }

    @Column(name = "longest_word", nullable = false, length = 65535)
    public String getLongestWord()
    {
        return this.longestWord;
    }

    public void setLongestWord(String longestWord)
    {
        this.longestWord = longestWord;
    }

    @Column(name = "shortest_word", nullable = false, length = 65535)
    public String getShortestWord()
    {
        return this.shortestWord;
    }

    public void setShortestWord(String shortestWord)
    {
        this.shortestWord = shortestWord;
    }

    @Column(name = "line_length", nullable = false)
    public int getLineLength()
    {
        return this.lineLength;
    }

    public void setLineLength(int lineLength)
    {
        this.lineLength = lineLength;
    }

    @Column(name = "avg_word_length", nullable = false, precision = 22, scale = 0)
    public double getAvgWordLength()
    {
        return this.avgWordLength;
    }

    public void setAvgWordLength(double avgWordLength)
    {
        this.avgWordLength = avgWordLength;
    }

}
